stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        npm install -g @angular/cli
        npm install
        npm run build
      displayName: 'npm install'
    
    - task: CmdLine@2
      displayName: "Build-prod"
      inputs:
        script: "npm run build-prod"

    # - task: CmdLine@2
    #   displayName: "Validate Angular violations"
    #   inputs:
    #     script: "npm run test:lint"

    # - task: CmdLine@2
    #   displayName: "Run Angular tests"
    #   inputs:
    #     script: "npm run test:unit"
    
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop